### ISSUE TITLE
Clicking any of the settings options fails and results in error

### ISSUE THREAD

**Issue by wetj** [ChromegleApp/Chromegle#14]
Once the settings button is clicked, a menu pops up with 4 different settings options: Greeting, Automation, Security, and Theme.
Clicking any of these four buttons does nothing, and results in an error in the console on each click:

`Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at HTMLDivElement.<anonymous> (menu.js:116:38)`

Google Chrome Version 109.0.5414.87 (Official Build)
Chromegle Extension Version 4.20 (installed from chrome web store)
*AND*
Chromegle Extension Version 4.20 (installed via developer mode from repository)

**Comment by isaackogan** [comment]
Disable one and confirm this still happens. Never have both at once

**Comment by isaackogan** [comment]
:( I will have to check when I get home

**Comment by isaackogan** [comment]
Can you please provide the full stacktrace of EVERYTHING in your console. A screenshot would be preferable

**Comment by isaackogan** [comment]
Nevermind, found & fixed
