### ISSUE TITLE
auto skip ip blacklisted ?

### ISSUE THREAD

**Issue by thomas59553** [ChromegleApp/Chromegle#2]
hello i would like auto skip ip blacklisted 
![blacklist](https://user-images.githubusercontent.com/54393167/148675302-26bff48f-47db-4190-8eb9-6a8863d2ff81.png)

**Comment by isaackogan** [comment]
Interesting, I'll look into this and let you know what went wrong

**Comment by isaackogan** [comment]
Fixed on latest version
