### ISSUE TITLE
Add keyboard shortcuts to text mode sidebar buttons 

### ISSUE THREAD

**Issue by MDeca001** [ChromegleApp/Chromegle#24]
I'd really love to have some keyboard shortcuts to paste the content configured in the sidebar buttons in text mode.
Might be something like `Alt` + `Shift` + `1-5` or something like that.

**Comment by isaackogan** [comment]
Make a pull request

**Comment by isaackogan** [comment]
I was hasty to close this. I'll look into implementing this...

**Comment by isaackogan** [comment]
Added in https://github.com/ChromegleApp/Chromegle/commit/e26a2d7cfd47057a0f7276776d7b14a33718b743
