### ISSUE TITLE
new feature strongly suggested

### ISSUE THREAD

**Issue by Saifoloyd** [ChromegleApp/Chromegle#3]
being able to block certain countries when being matched, like india, algeria, morocco, etc...

too many horny guy ruining the experiences and being able to auto skip certain countries in my block list would really make it ultimate.

**Comment by isaackogan** [comment]
No, and for why not, see the following scenario:

- I block America
- 50% of people on Omegle are American
- Chromegle skips 50% of people on Omegle
- Omegle detects you as a Spambot
- You are now banned
- You blame Chromegle

There is an individual IP-Blacklist for you to block specific individuals that are harming your experience on the platform. Let me know if you have any other ideas/disagree with this, etc.
