### ISSUE TITLE
Blocking Ip Ranges

### ISSUE THREAD

**Issue by stratte89** [ChromegleApp/Chromegle#5]
hey bro,

i love chromegle! Thank you so much for that extension.

i know someone asked that before, and you said you would more likely get noticed as a bot but i can deal with that. I would love to ban all India, Phillipines, Vietnam, Sri-lanka, Thailand, North South Korean , Taiwan, Egypt, Saudi Arabia, Israel, IP´s. 

How could i implement that?

Looking forward to your help :)

Have an amazing day :)

**Comment by HeisenbergOG** [comment]
Second

**Comment by stratte89** [comment]
Second?

**Comment by Sanakovich** [comment]
for dynamic IP's i don't think its possible but using a macro alongside with chomegle will do the job.

**Comment by stratte89** [comment]
tbh i have no idea about programming. I thought, since the IP Grabber can show the location it would be something like "if location=India =add ip to banlist or something.

**Comment by isaackogan** [comment]
I will add this in the next iteration of Chromegle with a warning about how it will probably get you banned for potential botting

**Comment by stratte89** [comment]
Amazing!  I dont think that it will ban you, but possibly getting captchas all the time. Well i modified your scripts a but and changed the ban delay to 0,5 sec so if a banned ip gets detected its waiting for 0,5 sec before skipping, that avoids getting captchas. Do you know yet when the next iteration will be uploaded? Or could you send a notification here so i wont miss it? Thank you very much!

**Comment by HeisenbergOG** [comment]
I skip people from those regions regardless and don't get banned for it. So I think it'll be safe for the most part.

**Comment by isaackogan** [comment]
Added in version 4.0
