### ISSUE TITLE
Auto-skip anyone with a black screen

### ISSUE THREAD

**Issue by sambragg** [ChromegleApp/Chromegle#6]
Frequently people use Omegle whilst they have a black screen, perhaps because they have put something over the top of their camera's lens to hide their identity. It seems to me that this behaviour isn't really conducive to having a decent conversation!

I suggest a way to detect users whose screen is black (perhaps if their screen doesn't change over an _n_ second period?), and then have the option to automatically skip such people.

Love the extension and keep up the great work devs!

**Comment by isaackogan** [comment]
I have a clever idea for this... Will get back to you

**Comment by isaackogan** [comment]
\*forgets to look into\*

**Comment by isaackogan** [comment]
Not gonna do this one.
